name: CI/CD Backend

on:
  push:
    branches:
      - main
    paths:
      - "backend/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    # Definimos variables globales para el job para no repetir código
    env:
      ECR_REPOSITORY: tienda-backend
      IMAGE_TAG: latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build & Push
        run: |
          cd backend
          docker build -t ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }} .
          docker push ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}

      - name: Deploy SSM
        run: |
          aws ssm send-command \
            --instance-ids ${{ secrets.EC2_BACKEND_INSTANCE_ID }} \
            --document-name "AWS-RunShellScript" \
            --comment "Update Backend" \
            --parameters '{
              "commands": [
                "set -e",
                "aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | sudo docker login --username AWS --password-stdin ${{ steps.login-ecr.outputs.registry }}",
                "sudo docker pull ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}",
                "sudo docker stop ${{ env.ECR_REPOSITORY }} || true",
                "sudo docker rm ${{ env.ECR_REPOSITORY }} || true",
                "sudo docker run -d --name ${{ env.ECR_REPOSITORY }} -p 3001:3001 ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}"
              ]
            }'